@startuml

:start;

:「明日」「あした」「1日後」
↓
「今日の日付+1」に置き換える;
note left:例　明日→10月22日

:日付検索;
:2桁以内の数字 + 月 + 2桁以内の数字 + 日
↓
日付として取得;
note left:例　10月22日は日付として取得
:時間検索;
:2桁以内の数字 + 時
↓
時間として取得;

note left:例　18時は時刻として取得

:end;

@enduml